// 日照ステップの自動テスト: 航空写真・周辺建物・部屋解析・日影図
import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--ignore-certificate-errors'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('404')) console.log('[console]', m.text()); });
const base = process.argv[2] ?? 'http://localhost:5173';
await page.goto(`${base}/?sample=sample_house_A3.pdf#sun`);
await page.waitForFunction(() => window.__ready === true, null, { timeout: 180000 });
const click = async (text) => { await page.getByRole('button', { name: text }).first().click(); };
await page.locator('input[placeholder^="例: "]').fill('東京都世田谷区奥沢3丁目');
await click('検索');
await page.getByRole('button', { name: /奥沢三丁目/ }).first().click({ timeout: 30000 });
await page.waitForTimeout(3000);
await page.waitForFunction(() => !document.querySelector('.modal-back'), null, { timeout: 120000 });
await page.waitForTimeout(4000);
await page.screenshot({ path: 'test-output/sun-aerial.png' });
const t0 = Date.now();
await click('部屋ごとの日当たりを解析');
await page.waitForFunction(() => !document.querySelector('.modal-back'), null, { timeout: 600000 });
console.log('room analysis sec', (Date.now() - t0) / 1000);
await page.locator('.side').evaluate((el) => el.scrollTo(0, el.scrollHeight));
await page.waitForTimeout(500);
await page.screenshot({ path: 'test-output/sun-rooms.png' });
const t1 = Date.now();
await click('日影図（GL+1.5m）');
await page.waitForSelector('.modal-body svg', { timeout: 600000 });
console.log('diagram sec', (Date.now() - t1) / 1000);
await page.waitForTimeout(500);
await page.screenshot({ path: 'test-output/sun-diagram.png' });
await browser.close();
